// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaEscolaDigital.Infrastructure.Persistence;

namespace MinhaEscolaDigital.Infrastructure.Migrations
{
    [DbContext(typeof(MinhaEscolaDigitalDbContext))]
    partial class MinhaEscolaDigitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ObservacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[EnderecoId] IS NOT NULL");

                    b.HasIndex("ObservacaoId")
                        .IsUnique()
                        .HasFilter("[ObservacaoId] IS NOT NULL");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.AlunoResponsavel", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlunoId", "ResponsavelId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("AlunosResponsaveis");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Escola", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ObservacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[EnderecoId] IS NOT NULL");

                    b.HasIndex("ObservacaoId");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Observacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.HasKey("Id");

                    b.ToTable("Observacoes");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ObservacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObservacaoId")
                        .IsUnique()
                        .HasFilter("[ObservacaoId] IS NOT NULL");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.ResumoDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataResumo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("ResumosDias");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EscolaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ObservacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("ObservacaoId")
                        .IsUnique()
                        .HasFilter("[ObservacaoId] IS NOT NULL");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("MinhaEscolaDigital.Domain.Entities.Aluno", "EnderecoId");

                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Observacao", "Observacao")
                        .WithOne()
                        .HasForeignKey("MinhaEscolaDigital.Domain.Entities.Aluno", "ObservacaoId");

                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("AlunoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("AlunoId");

                            b1.ToTable("Alunos");

                            b1.WithOwner()
                                .HasForeignKey("AlunoId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Rg", "Rg", b1 =>
                        {
                            b1.Property<Guid>("AlunoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("Rg");

                            b1.HasKey("AlunoId");

                            b1.ToTable("Alunos");

                            b1.WithOwner()
                                .HasForeignKey("AlunoId");
                        });

                    b.Navigation("Cpf");

                    b.Navigation("Endereco");

                    b.Navigation("Observacao");

                    b.Navigation("Rg");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.AlunoResponsavel", b =>
                {
                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Aluno", "Aluno")
                        .WithMany("AlunosResponsaveis")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Responsavel", "Responsavel")
                        .WithMany("AlunosResponsaveis")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Escola", b =>
                {
                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("MinhaEscolaDigital.Domain.Entities.Escola", "EnderecoId");

                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Observacao", "Observacao")
                        .WithMany()
                        .HasForeignKey("ObservacaoId");

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("EscolaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("Cpnj");

                            b1.HasKey("EscolaId");

                            b1.ToTable("Escolas");

                            b1.WithOwner()
                                .HasForeignKey("EscolaId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("EscolaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("EscolaId");

                            b1.ToTable("Escolas");

                            b1.WithOwner()
                                .HasForeignKey("EscolaId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Telefone", "Celular", b1 =>
                        {
                            b1.Property<Guid>("EscolaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("varchar(13)")
                                .HasColumnName("Celular");

                            b1.HasKey("EscolaId");

                            b1.ToTable("Escolas");

                            b1.WithOwner()
                                .HasForeignKey("EscolaId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("EscolaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("varchar(13)")
                                .HasColumnName("Telefone");

                            b1.HasKey("EscolaId");

                            b1.ToTable("Escolas");

                            b1.WithOwner()
                                .HasForeignKey("EscolaId");
                        });

                    b.Navigation("Celular");

                    b.Navigation("Cnpj");

                    b.Navigation("Email");

                    b.Navigation("Endereco");

                    b.Navigation("Observacao");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Responsavel", b =>
                {
                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Observacao", "Observacao")
                        .WithOne()
                        .HasForeignKey("MinhaEscolaDigital.Domain.Entities.Responsavel", "ObservacaoId");

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("ResponsavelId");

                            b1.ToTable("Responsaveis");

                            b1.WithOwner()
                                .HasForeignKey("ResponsavelId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("ResponsavelId");

                            b1.ToTable("Responsaveis");

                            b1.WithOwner()
                                .HasForeignKey("ResponsavelId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Rg", "Rg", b1 =>
                        {
                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("Rg");

                            b1.HasKey("ResponsavelId");

                            b1.ToTable("Responsaveis");

                            b1.WithOwner()
                                .HasForeignKey("ResponsavelId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Telefone", "Celular", b1 =>
                        {
                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("varchar(13)")
                                .HasColumnName("Celular");

                            b1.HasKey("ResponsavelId");

                            b1.ToTable("Responsaveis");

                            b1.WithOwner()
                                .HasForeignKey("ResponsavelId");
                        });

                    b.OwnsOne("MinhaEscolaDigital.Domain.DomainObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("varchar(13)")
                                .HasColumnName("Telefone");

                            b1.HasKey("ResponsavelId");

                            b1.ToTable("Responsaveis");

                            b1.WithOwner()
                                .HasForeignKey("ResponsavelId");
                        });

                    b.Navigation("Celular");

                    b.Navigation("Cpf");

                    b.Navigation("Email");

                    b.Navigation("Observacao");

                    b.Navigation("Rg");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.ResumoDia", b =>
                {
                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Resumos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Turma", b =>
                {
                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Escola", "Escola")
                        .WithMany("Turmas")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaEscolaDigital.Domain.Entities.Observacao", "Observacao")
                        .WithOne()
                        .HasForeignKey("MinhaEscolaDigital.Domain.Entities.Turma", "ObservacaoId");

                    b.Navigation("Escola");

                    b.Navigation("Observacao");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("AlunosResponsaveis");

                    b.Navigation("Resumos");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Escola", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Responsavel", b =>
                {
                    b.Navigation("AlunosResponsaveis");
                });

            modelBuilder.Entity("MinhaEscolaDigital.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
